/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proje2;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hacerebra
 */
public class HacerEbraOzdemir_Frm_Maas extends javax.swing.JFrame {

    HacerEbraOzdemir_Personel personel;//Personel sinifindan personel adinda bir nesne tanimlanir.
    DefaultTableModel tbl_maas_model;//tbl_maas_model adinda bir nesne tanimlanir. 

    public HacerEbraOzdemir_Frm_Maas(HacerEbraOzdemir_Personel personel) {

        initComponents();
        this.personel = personel;//Sinifin personel degiskeni, yapicidaki personel parametresiyle atanir.
        lbl_personelIsım.setText(personel.ad_soyad + " / " + personel.pozisyon);//lbl_personelIsım uzerindeki metin, personel nesnesinin ad_soyad ve pozisyon ozellikleri kullanilarak olusturulur. Bu, kullanicinin hangi personelin maas bilgilerini goruntulendigini gosteren bir metin saglar.
        tbl_maas_model = new DefaultTableModel();//Maas tablosunun veri modelini temsil eder.
        tbl_maas_model.setColumnIdentifiers(new Object[]{"MAAŞ TÜRÜ", "MAAŞ"});//Tablonun sutun basliklari ayarlanir.
        tbl_maas.setModel(tbl_maas_model);//Maas tablosuna tbl_maas_model nesnesi atanir.
        SetMaasToTable();//Maas bilgilerini tabloya yerlestirilir.
    }

    //Bu method, veritabanindan alinan maas bilgilerini alir ve her bir maas kaydini tabloya ekler. 
    private void SetMaasToTable() {

        ArrayList<HacerEbraOzdemir_Maas> maaslar = HacerEbraOzdemir_DB_PersonelTakip.GetMaas();//"DB_PersonelTakip" sinifindan "GetMaas" methodu cagrilir ve bu yontemden donen maas bilgileri bir ArrayList<Maas> nesnesine atanir. Bu, veritabanindan tüm maas bilgilerini almayi saglar.
        tbl_maas_model.setRowCount(0);//tbl_maas_model nesnesinin satir sayisi sifirlanir. Bu, tablonun mevcut satirlarini temizler.
        for (HacerEbraOzdemir_Maas maas : maaslar) {
            tbl_maas_model.addRow(new Object[]{maas.maas_turu, maas.maas});//Maas turu ve maas degeri tabloya eklenir.

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_maas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_maas = new javax.swing.JTable();
        btn_maasEkle = new javax.swing.JButton();
        btn_maasSil = new javax.swing.JButton();
        lbl_personelIsım = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        pnl_maas.setBackground(new java.awt.Color(102, 0, 153));
        pnl_maas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MAAŞ KONTROLÜ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 1, 15), new java.awt.Color(255, 255, 0))); // NOI18N

        jScrollPane1.setBorder(null);

        tbl_maas.setBackground(new java.awt.Color(255, 255, 204));
        jScrollPane1.setViewportView(tbl_maas);

        btn_maasEkle.setBackground(new java.awt.Color(255, 255, 153));
        btn_maasEkle.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btn_maasEkle.setForeground(new java.awt.Color(102, 0, 153));
        btn_maasEkle.setText("MAAŞ EKLE");
        btn_maasEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_maasEkleActionPerformed(evt);
            }
        });

        btn_maasSil.setBackground(new java.awt.Color(255, 255, 153));
        btn_maasSil.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btn_maasSil.setForeground(new java.awt.Color(102, 0, 153));
        btn_maasSil.setText("MAAŞ SİL");
        btn_maasSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_maasSilActionPerformed(evt);
            }
        });

        lbl_personelIsım.setFont(new java.awt.Font("Helvetica Neue", 2, 14)); // NOI18N
        lbl_personelIsım.setForeground(new java.awt.Color(255, 255, 0));
        lbl_personelIsım.setText("AD SOYAD");

        javax.swing.GroupLayout pnl_maasLayout = new javax.swing.GroupLayout(pnl_maas);
        pnl_maas.setLayout(pnl_maasLayout);
        pnl_maasLayout.setHorizontalGroup(
            pnl_maasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_maasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_maasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(pnl_maasLayout.createSequentialGroup()
                        .addComponent(btn_maasEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_maasSil, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_personelIsım, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_maasLayout.setVerticalGroup(
            pnl_maasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_maasLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(lbl_personelIsım)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_maasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_maasEkle)
                    .addComponent(btn_maasSil))
                .addContainerGap())
        );

        getContentPane().add(pnl_maas);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Bu method, kullanicinin "tbl_maas" tablosundan secili bir maas kaydini secilen personele eklemesini saglar. 
    private void btn_maasEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_maasEkleActionPerformed

        if (tbl_maas.getSelectedRow() < 0) {//tbl_maas tablosunda herhangi bir satirin secili olup olmadigi kontrol edilir.
            return;
        }

        String maas = (String) tbl_maas_model.getValueAt(tbl_maas.getSelectedRow(), 1);//Secili satirdaki 1. sutundaki deger (maas) alinir ve bir dize olarak maas degiskenine atanir.
        HacerEbraOzdemir_DB_PersonelTakip.PersoneleMaasEkle(this.personel.ad_soyad, maas);//DB_PersonelTakip sinifindan PersoneleMaasEkle methodu cagrilir ve this.personel.ad_soyad ve maas degiskenleri bu methoda parametre olarak verilir. Secilen personele belirli bir maas degerinin eklenmesini saglar.
    }//GEN-LAST:event_btn_maasEkleActionPerformed

    //Bu method, kullanicinin "tbl_maas" tablosundan secili bir maas kaydini secili personele silmesini saglar. 
    private void btn_maasSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_maasSilActionPerformed

        if (tbl_maas.getSelectedRow() < 0) {//tbl_maas tablosunda herhangi bir satirin secili olup olmadigi kontrol edilir.
            return;
        }

        String maas = (String) tbl_maas_model.getValueAt(tbl_maas.getSelectedRow(), 1);//Secili satirdaki 1. sutundaki deger (maas) alinir ve bir dize olarak maas degiskenine atanir.
        HacerEbraOzdemir_DB_PersonelTakip.PersoneldenMaasSil(this.personel.ad_soyad, maas);//DB_PersonelTakip sinifindan PersoneldenMaasSil methodu cagrilir ve this.personel.ad_soyad ve maas degiskenleri bu methoda parametre olarak verilir. Secilen personele belirli bir maas degerinin eklenmesini saglar.
    }//GEN-LAST:event_btn_maasSilActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_maasEkle;
    private javax.swing.JButton btn_maasSil;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_personelIsım;
    private javax.swing.JPanel pnl_maas;
    private javax.swing.JTable tbl_maas;
    // End of variables declaration//GEN-END:variables
}
