/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proje2;

import javax.swing.JOptionPane;

/**
 *
 * @author hacerebra
 */
public class HacerEbraOzdemir_Frm_Personel extends javax.swing.JFrame {

    HacerEbraOzdemir_Personel personel;//Personel sinifindan personel adinda bir nesne tanimlanir.

    //Frm_Personel yapici metodudur ve formun baslatilmasi ve personel bilgilerinin ilgili etiketlere atanmasi islemlerini gerceklestirir.
    public HacerEbraOzdemir_Frm_Personel(HacerEbraOzdemir_Personel personel) {
        initComponents();
        this.personel = personel;//Sinifin personel degiskeni, yapicidaki personel parametresiyle atanir.

        //Penceredeki labellara personelin bilgileri atanir.
        lbl_pAd.setText(personel.ad_soyad);
        lbl_pCinsiyet.setText(personel.cinsiyet);
        lbl_pMail.setText(personel.mail);
        lbl_pPozisyon.setText(personel.pozisyon);
        if (personel.calisma_saati == true) {
            lbl_pCalısmaSaati.setText("Tam Zamanlı");
        } else {
            lbl_pCalısmaSaati.setText("Yarı Zamanlı");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_personel = new javax.swing.JPanel();
        lbl_cinsiyetPersonel = new javax.swing.JLabel();
        lbl_mailPersonel = new javax.swing.JLabel();
        lbl_pozisypnPersonel = new javax.swing.JLabel();
        btn_izinGunuGor = new javax.swing.JButton();
        lbl_pAd = new javax.swing.JLabel();
        lbl_pCinsiyet = new javax.swing.JLabel();
        lbl_pMail = new javax.swing.JLabel();
        lbl_pPozisyon = new javax.swing.JLabel();
        lbl_adPersonel = new javax.swing.JLabel();
        btn_maasGor = new javax.swing.JButton();
        lbl_calismasPersonel = new javax.swing.JLabel();
        lbl_pCalısmaSaati = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        pnl_personel.setBackground(new java.awt.Color(102, 0, 204));
        pnl_personel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PERSONEL BİLGİLERİ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 3, 16), new java.awt.Color(255, 255, 0))); // NOI18N

        lbl_cinsiyetPersonel.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        lbl_cinsiyetPersonel.setForeground(new java.awt.Color(255, 255, 0));
        lbl_cinsiyetPersonel.setText("CİNSİYET");

        lbl_mailPersonel.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        lbl_mailPersonel.setForeground(new java.awt.Color(255, 255, 0));
        lbl_mailPersonel.setText("MAİL");

        lbl_pozisypnPersonel.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        lbl_pozisypnPersonel.setForeground(new java.awt.Color(255, 255, 0));
        lbl_pozisypnPersonel.setText("POZİSYON");

        btn_izinGunuGor.setBackground(new java.awt.Color(255, 255, 204));
        btn_izinGunuGor.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btn_izinGunuGor.setForeground(new java.awt.Color(102, 0, 153));
        btn_izinGunuGor.setText("İZİN GÜNLERİNİ GÖR");
        btn_izinGunuGor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_izinGunuGorActionPerformed(evt);
            }
        });

        lbl_pAd.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lbl_pAd.setForeground(new java.awt.Color(204, 204, 255));
        lbl_pAd.setText("jLabel5");

        lbl_pCinsiyet.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lbl_pCinsiyet.setForeground(new java.awt.Color(204, 204, 255));
        lbl_pCinsiyet.setText("jLabel6");

        lbl_pMail.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lbl_pMail.setForeground(new java.awt.Color(204, 204, 255));
        lbl_pMail.setText("jLabel7");

        lbl_pPozisyon.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lbl_pPozisyon.setForeground(new java.awt.Color(204, 204, 255));
        lbl_pPozisyon.setText("jLabel8");

        lbl_adPersonel.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        lbl_adPersonel.setForeground(new java.awt.Color(255, 255, 0));
        lbl_adPersonel.setText("AD SOYAD");

        btn_maasGor.setBackground(new java.awt.Color(255, 255, 204));
        btn_maasGor.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btn_maasGor.setForeground(new java.awt.Color(102, 0, 153));
        btn_maasGor.setText("MAAŞ LİSTESİ GÖR");
        btn_maasGor.setMaximumSize(new java.awt.Dimension(166, 23));
        btn_maasGor.setMinimumSize(new java.awt.Dimension(166, 23));
        btn_maasGor.setPreferredSize(new java.awt.Dimension(166, 23));
        btn_maasGor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_maasGorActionPerformed(evt);
            }
        });

        lbl_calismasPersonel.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        lbl_calismasPersonel.setForeground(new java.awt.Color(255, 255, 0));
        lbl_calismasPersonel.setText("ÇALIŞMA SAATİ");

        lbl_pCalısmaSaati.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lbl_pCalısmaSaati.setForeground(new java.awt.Color(204, 204, 255));
        lbl_pCalısmaSaati.setText("jLabel1");

        javax.swing.GroupLayout pnl_personelLayout = new javax.swing.GroupLayout(pnl_personel);
        pnl_personel.setLayout(pnl_personelLayout);
        pnl_personelLayout.setHorizontalGroup(
            pnl_personelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_personelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_personelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_izinGunuGor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_maasGor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnl_personelLayout.createSequentialGroup()
                        .addComponent(lbl_calismasPersonel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_pCalısmaSaati)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnl_personelLayout.createSequentialGroup()
                        .addGroup(pnl_personelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_mailPersonel)
                            .addComponent(lbl_pozisypnPersonel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_cinsiyetPersonel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_adPersonel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(pnl_personelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_personelLayout.createSequentialGroup()
                                .addComponent(lbl_pAd, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                .addGap(52, 52, 52))
                            .addComponent(lbl_pCinsiyet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_pPozisyon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_pMail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        pnl_personelLayout.setVerticalGroup(
            pnl_personelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_personelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_personelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_pAd)
                    .addComponent(lbl_adPersonel))
                .addGap(19, 19, 19)
                .addGroup(pnl_personelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cinsiyetPersonel)
                    .addComponent(lbl_pCinsiyet))
                .addGap(18, 18, 18)
                .addGroup(pnl_personelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_mailPersonel)
                    .addComponent(lbl_pMail))
                .addGap(18, 18, 18)
                .addGroup(pnl_personelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_pozisypnPersonel)
                    .addComponent(lbl_pPozisyon))
                .addGap(18, 18, 18)
                .addGroup(pnl_personelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_calismasPersonel)
                    .addComponent(lbl_pCalısmaSaati))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(btn_maasGor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_izinGunuGor)
                .addGap(18, 18, 18))
        );

        getContentPane().add(pnl_personel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Bu method, ilgili personelin maas bilgilerini gosterir ve kullanicinin bu bilgilere sadece bakmasina izin verir, duzenleme yapmasina izin vermez.
    private void btn_maasGorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_maasGorActionPerformed

        HacerEbraOzdemir_Frm_Maas frm_Maas = new HacerEbraOzdemir_Frm_Maas(personel);//Frm_Maas sinifindan bir frm_Maas nesnesi olusturulur.
        frm_Maas.setVisible(true);//frm_Maas penceresi kullaniciya goruntulenir.
        frm_Maas.setEnabled(false);//Kullanıcinin frm_Maas penceresindeki bilesenlere erisimini devre disi birakir.
    }//GEN-LAST:event_btn_maasGorActionPerformed

    private void btn_izinGunuGorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_izinGunuGorActionPerformed

        HacerEbraOzdemir_Frm_IzinGunu frm_IzinGunu = new HacerEbraOzdemir_Frm_IzinGunu(personel);//Frm_IzinGunu sinifindan bir frm_IzinGunu nesnesi olusturulur.
        frm_IzinGunu.setVisible(true);//frm_IzinGunu penceresi kullaniciya goruntulenir.
        frm_IzinGunu.btn_tumunuGor.doClick();//Izinleri gosteren tabloyu gunceller.
        //Personelin izin ekleme ve silme islemlerini devre disi birakir.
        frm_IzinGunu.btn_izinEkle.setEnabled(false);
        frm_IzinGunu.btn_izinSil.setEnabled(false);
        frm_IzinGunu.txt_personelAd.setText(personel.ad_soyad);//txt_personelAd adli metin alanina, ilgili personelin adi ve soyadi yazilir.
        int izin_sayisi = 0;

        for (int row = 0; row < frm_IzinGunu.tbl_model.getRowCount(); row++) {
            String personelAdi = (String) frm_IzinGunu.tbl_model.getValueAt(row, 0);//frm_IzinGunu nesnesinin tablosundan bir personel adi alinir.
            if (personelAdi.equals(personel.ad_soyad)) {//Eger bu personel adi, ilgili personelin adiyla eslesiyorsa, izin_sayisi degiskeni bir artirilir.
                izin_sayisi++;
            }
        }
        //Kullaniciya personelin adini ve hesaplanan izin gunu sayisini iceren bir mesaj gosterilir. 
        JOptionPane.showMessageDialog(null, personel.ad_soyad + " 'in izin günü sayısı: " + Integer.toString(izin_sayisi));
    }//GEN-LAST:event_btn_izinGunuGorActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_izinGunuGor;
    private javax.swing.JButton btn_maasGor;
    private javax.swing.JLabel lbl_adPersonel;
    private javax.swing.JLabel lbl_calismasPersonel;
    private javax.swing.JLabel lbl_cinsiyetPersonel;
    private javax.swing.JLabel lbl_mailPersonel;
    private javax.swing.JLabel lbl_pAd;
    private javax.swing.JLabel lbl_pCalısmaSaati;
    private javax.swing.JLabel lbl_pCinsiyet;
    private javax.swing.JLabel lbl_pMail;
    private javax.swing.JLabel lbl_pPozisyon;
    private javax.swing.JLabel lbl_pozisypnPersonel;
    private javax.swing.JPanel pnl_personel;
    // End of variables declaration//GEN-END:variables
}
