/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proje2;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hacerebra
 */
public class HacerEbraOzdemir_Frm_IzinGunu extends javax.swing.JFrame {

    DefaultTableModel tbl_model;//tbl_model adinda bir nesne tanimlanir. 
    HacerEbraOzdemir_Personel personel;//Personel sinifindan personel adinda bir nesne tanimlanir.

    //Frm_IzinGunu adinda bir yapıcı tanimlanir. Bu yapici, Personel turunden bir parametre alir. 
    public HacerEbraOzdemir_Frm_IzinGunu(HacerEbraOzdemir_Personel personel) {
        initComponents();
        this.personel = personel;//Sinifin personel degiskeni, yapicidaki personel parametresiyle atanir.
        tbl_model = new DefaultTableModel();
        tbl_model.setColumnIdentifiers(new Object[]{"AD SOYAD", "TARİH"});//tbl_model icin sutun basliklari belirlenir.
        tbl_izinGunu.setModel(tbl_model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_izinGunu = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_izinGunu = new javax.swing.JTable();
        btn_izinEkle = new javax.swing.JButton();
        btn_izinSil = new javax.swing.JButton();
        lbl_tarih = new javax.swing.JLabel();
        txt_tarih = new javax.swing.JTextField();
        txt_personelAd = new javax.swing.JTextField();
        lbl_ad = new javax.swing.JLabel();
        btn_tumunuGor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        pnl_izinGunu.setBackground(new java.awt.Color(153, 153, 255));
        pnl_izinGunu.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PERSONEL İZİN GÜNÜ KONTROLÜ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 3, 16), new java.awt.Color(255, 255, 0))); // NOI18N

        tbl_izinGunu.setBackground(new java.awt.Color(255, 255, 204));
        tbl_izinGunu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "AD SOYAD", "TARİH"
            }
        ));
        tbl_izinGunu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_izinGunuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_izinGunu);

        btn_izinEkle.setBackground(new java.awt.Color(102, 0, 204));
        btn_izinEkle.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btn_izinEkle.setForeground(new java.awt.Color(255, 255, 102));
        btn_izinEkle.setText("İZİN GÜNÜ EKLE");
        btn_izinEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_izinEkleActionPerformed(evt);
            }
        });

        btn_izinSil.setBackground(new java.awt.Color(102, 0, 204));
        btn_izinSil.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btn_izinSil.setForeground(new java.awt.Color(255, 255, 102));
        btn_izinSil.setText("İZİN GÜNÜ SİL");
        btn_izinSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_izinSilActionPerformed(evt);
            }
        });

        lbl_tarih.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lbl_tarih.setForeground(new java.awt.Color(255, 255, 0));
        lbl_tarih.setText("TARİH");

        lbl_ad.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lbl_ad.setForeground(new java.awt.Color(255, 255, 0));
        lbl_ad.setText("AD SOYAD");

        btn_tumunuGor.setBackground(new java.awt.Color(102, 0, 204));
        btn_tumunuGor.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btn_tumunuGor.setForeground(new java.awt.Color(255, 255, 102));
        btn_tumunuGor.setText("TÜMÜNÜ GÖR");
        btn_tumunuGor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tumunuGorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_izinGunuLayout = new javax.swing.GroupLayout(pnl_izinGunu);
        pnl_izinGunu.setLayout(pnl_izinGunuLayout);
        pnl_izinGunuLayout.setHorizontalGroup(
            pnl_izinGunuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_izinGunuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_izinGunuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_izinSil, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                    .addComponent(btn_izinEkle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnl_izinGunuLayout.createSequentialGroup()
                        .addGroup(pnl_izinGunuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_tarih, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_ad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_izinGunuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_personelAd)
                            .addComponent(txt_tarih)))
                    .addComponent(btn_tumunuGor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnl_izinGunuLayout.setVerticalGroup(
            pnl_izinGunuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_izinGunuLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(pnl_izinGunuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnl_izinGunuLayout.createSequentialGroup()
                        .addGroup(pnl_izinGunuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_personelAd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_ad))
                        .addGap(18, 18, 18)
                        .addGroup(pnl_izinGunuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_tarih)
                            .addComponent(txt_tarih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btn_izinEkle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_izinSil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_tumunuGor)
                        .addGap(25, 25, 25)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pnl_izinGunu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_izinEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_izinEkleActionPerformed

        HacerEbraOzdemir_Personel np1 = new HacerEbraOzdemir_Personel();//Personel nesnesi (np1) olusturulur.
        String regex = "^(0[1-9]|1\\d|2\\d|3[01])/(0[1-9]|1[0-2])/\\d{4}$";//Gecerli bir tarih formatini tanimlayan bir düzenli ifade (regex) olusturulur. Bu regex, gun/ay/yıl formati kontrol etmek icin kullanilir.
        np1.ad_soyad = txt_personelAd.getText();//Metin kutusundan (txt_personelAd) alinan deger, np1 nesnesinin ad_soyad ozelligine atanir.
        np1.izin = txt_tarih.getText();//Metin kutusundan (txt_tarih) alinan deger, np1 nesnesinin izin ozelligine atanir. Bu, izin tarihini temsil eder.

        if (np1.izin.matches(regex)) {//np1.izin degeri, regexe uyan bir formatta mi kontrol edilir.
            HacerEbraOzdemir_DB_PersonelTakip.IzinGunuEkle(np1, np1.izin);//DB_PersonelTakip adli bir sinifin IzinGunuEkle methodu cagrilir ve np1 nesnesi ve izin tarihi methoda parametre olarak verilir. Bu, izin bilgilerini veritabanina ekler.
            tbl_model.addRow(new Object[]{np1.ad_soyad, np1.izin});//Tabloya yeni bir izin kaydi ekler.
            JOptionPane.showMessageDialog(rootPane, "İzin girişi tamamlanmıştır.");//Kullaniciya "İzin girisi tamamlanmistir." mesaji gosterilir.
        } else {
            JOptionPane.showMessageDialog(rootPane, "Tarih yanlış formatlı.");//Eger izin tarihi gecerli bir formatta degilse, kullaniciya "Tarih yanlis formatli." mesaji gosterilir. 
        }
    }//GEN-LAST:event_btn_izinEkleActionPerformed

    //Belirli bir arama kriterine gore izin bilgilerini veritabanindan alir ve bu bilgileri tabloya ekler, boylece kullanici tum izinleri goruntuleyebilir.
    private void btn_tumunuGorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tumunuGorActionPerformed

        String arama = txt_personelAd.getText();//arama adli bir dize degiskenine atanir. Bu deger, arama sorgusu olarak kullanilacak.
        tbl_model.setRowCount(0);//Tablonun içerigi sifirlanir.
        ArrayList<HacerEbraOzdemir_Personel> plist = HacerEbraOzdemir_DB_PersonelTakip.IzinGoster(arama);//DB_PersonelTakip adli bir sinifin IzinGoster methodu cagrilir ve arama degiskeni bu methoda parametre olarak verilir. Bu, veritabaninda belirli bir arama kriterine gore izin bilgilerini alir ve bir ArrayList nesnesine atar. 

        for (HacerEbraOzdemir_Personel np1 : plist) {//Dongu, plist listesindeki her Personel nesnesi icin tekrarlanir.
            tbl_model.addRow(new Object[]{np1.ad_soyad, np1.izin});//Tabloya her bir Personel nesnesinin adi-soyadi ve izin tarihi bilgilerini eklenir.
        }
    }//GEN-LAST:event_btn_tumunuGorActionPerformed

    private void tbl_izinGunuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_izinGunuMouseClicked

        if (tbl_izinGunu.getSelectedRow() < 0) {//tbl_izinGunu tablosunda herhangi bir satirin secili olup olmadigi kontrol edilir.
            return;
        }

        String isim = tbl_model.getValueAt(tbl_izinGunu.getSelectedRow(), 0).toString();//Secili satirdaki 0. sutundaki deger (isim) alinir ve bir dize olarak isim degiskenine atanir.
        String izin_gunu = tbl_model.getValueAt(tbl_izinGunu.getSelectedRow(), 1).toString();//Secili satirdaki 1. sutundaki deger (izin_gunu) alinir ve bir dize olarak izin_gunu degiskenine atanir.
        ArrayList<HacerEbraOzdemir_Personel> plist = HacerEbraOzdemir_DB_PersonelTakip.IzinGoster(isim);//DB_PersonelTakip sinifindaki IzinGoster methodu cagrilir ve isim (secili satirdaki isim) degiskeni bu yonteme parametre olarak verilir. Bu, veritabaninda belirli bir isimle iliskili izin bilgilerini alir ve bir ArrayList nesnesine atar. 

        for (HacerEbraOzdemir_Personel np1 : plist) {//Dongu, plist listesindeki her Personel nesnesi icin tekrarlanir.
            if (np1 != null) {//np1 nesnesi null degilse;
                txt_personelAd.setText(np1.ad_soyad);//Metin kutusunun (txt_personelAd) icerigi, np1 nesnesinin ad_soyad ozelligi ile guncellenir.
                txt_tarih.setText(izin_gunu);//Metin kutusunun (txt_personelAd) icerigi, izin_gunu degiskeni ile guncellenir.

            }
        }
    }//GEN-LAST:event_tbl_izinGunuMouseClicked

    //Kullanicinin "tbl_izinGunu" tablosundan secili bir satiri silebilmesini saglar. Secilen izin kaydi, veritabanindan silinir ve kullaniciya bir mesaj gosterilir.
    private void btn_izinSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_izinSilActionPerformed

        if (tbl_izinGunu.getSelectedRow() < 0) {//tbl_izinGunu tablosunda herhangi bir satirin secili olup olmadigi kontrol edilir.
            return;
        }

        String isim = tbl_model.getValueAt(tbl_izinGunu.getSelectedRow(), 0).toString();//Secili satirdaki 0. sutundaki deger (isim) alinir ve bir dize olarak isim degiskenine atanir.
        String izin = (String) tbl_model.getValueAt(tbl_izinGunu.getSelectedRow(), 1);//Secili satirdaki 1. sutundaki deger (izin_gunu) alinir ve bir dize olarak izin_gunu degiskenine atanir.
        HacerEbraOzdemir_DB_PersonelTakip.PersoneldenIzinSil(isim, izin);//DB_PersonelTakip sinifindaki PersoneldenIzinSil methodu cagrilir ve isim ve izin degiskenleri bu methoda parametre olarak verilir. Bu, veritabaninda belirli bir isim ve izin gunune sahip izin kaydini siler.
        JOptionPane.showMessageDialog(rootPane, "İzin silindi.");//Kullaniciya "İzin silindi." mesaji gosterilir.
    }//GEN-LAST:event_btn_izinSilActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_izinEkle;
    public javax.swing.JButton btn_izinSil;
    public javax.swing.JButton btn_tumunuGor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_ad;
    private javax.swing.JLabel lbl_tarih;
    public javax.swing.JPanel pnl_izinGunu;
    private javax.swing.JTable tbl_izinGunu;
    public javax.swing.JTextField txt_personelAd;
    private javax.swing.JTextField txt_tarih;
    // End of variables declaration//GEN-END:variables
}
