/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proje2;

import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hacerebra
 */
public class HacerEbraOzdemir_Frm_Yonetici extends javax.swing.JFrame {

    ArrayList<HacerEbraOzdemir_Personel> personels = new ArrayList<>();//ArrayList<Personel> turunden bir degisken olan "personels" tanimlanmistir. 
    DefaultTableModel tbl_model;//tbl_model adinda bir nesne tanimlanir. 
    HacerEbraOzdemir_Yonetici yonetici;//Yonetici sinifindan yonetici adinda bir nesne tanimlanir.

    public HacerEbraOzdemir_Frm_Yonetici(HacerEbraOzdemir_Yonetici yonetici) {

        initComponents();
        this.yonetici = yonetici;//Sinifin yonetici degiskeni, yapicidaki yonetici parametresiyle atanir.
        tbl_model = new DefaultTableModel();//Personel tablosunun veri modelini temsil eder.
        tbl_model.setColumnIdentifiers(new Object[]{"ID", "AD SOYAD", "POZİSYON", "MAİL"});//Tablonun sutun basliklari ayarlanir.
        tbl_personel.setModel(tbl_model);//Personel tablosuna tbl_model nesnesi atanir.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngroup_saat = new javax.swing.ButtonGroup();
        btngroup_cinsiyet = new javax.swing.ButtonGroup();
        pnl_yonetici = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_personel = new javax.swing.JTable();
        lbl_tablo = new javax.swing.JLabel();
        btn_personelSil = new javax.swing.JButton();
        btn_personelGuncelle = new javax.swing.JButton();
        lbl_adSoyad = new javax.swing.JLabel();
        lbl_mail = new javax.swing.JLabel();
        lbl_sifre = new javax.swing.JLabel();
        lbl_pozisyon = new javax.swing.JLabel();
        lbl_saat = new javax.swing.JLabel();
        txt_adSoyad = new javax.swing.JTextField();
        txt_mail = new javax.swing.JTextField();
        txt_sifre = new javax.swing.JPasswordField();
        cbox_pozisyon = new javax.swing.JComboBox<>();
        btn_personelEkle = new javax.swing.JButton();
        lbl_arama = new javax.swing.JLabel();
        txt_personelArama = new javax.swing.JTextField();
        btn_ara = new javax.swing.JButton();
        btn_izinGunuKontrol = new javax.swing.JButton();
        lbl_id = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cbox_fullTime = new javax.swing.JCheckBox();
        cbox_cinsiyet = new javax.swing.JComboBox<>();
        btn_maasKontrol = new javax.swing.JButton();
        menubar = new javax.swing.JMenuBar();
        menu_islemler = new javax.swing.JMenu();
        menui_ekle = new javax.swing.JMenuItem();
        menui_güncelle = new javax.swing.JMenuItem();
        menui_sil = new javax.swing.JMenuItem();
        menu_arama = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        pnl_yonetici.setBackground(new java.awt.Color(204, 204, 255));

        tbl_personel.setBackground(new java.awt.Color(255, 255, 204));
        tbl_personel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_personelMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_personel);

        lbl_tablo.setFont(new java.awt.Font("Helvetica Neue", 3, 16)); // NOI18N
        lbl_tablo.setForeground(new java.awt.Color(51, 0, 153));
        lbl_tablo.setText("PERSONEL TABLOSU");

        btn_personelSil.setBackground(new java.awt.Color(102, 0, 255));
        btn_personelSil.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btn_personelSil.setForeground(new java.awt.Color(255, 255, 102));
        btn_personelSil.setText("PERSONEL SİL");
        btn_personelSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_personelSilActionPerformed(evt);
            }
        });

        btn_personelGuncelle.setBackground(new java.awt.Color(102, 0, 255));
        btn_personelGuncelle.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btn_personelGuncelle.setForeground(new java.awt.Color(255, 255, 102));
        btn_personelGuncelle.setText("PERSONEL GÜNCELLE");
        btn_personelGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_personelGuncelleActionPerformed(evt);
            }
        });

        lbl_adSoyad.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lbl_adSoyad.setForeground(new java.awt.Color(51, 0, 153));
        lbl_adSoyad.setText("AD SOYAD");

        lbl_mail.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lbl_mail.setForeground(new java.awt.Color(51, 0, 153));
        lbl_mail.setText("MAIL");

        lbl_sifre.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lbl_sifre.setForeground(new java.awt.Color(51, 0, 153));
        lbl_sifre.setText("ŞİFRE");

        lbl_pozisyon.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lbl_pozisyon.setForeground(new java.awt.Color(51, 0, 153));
        lbl_pozisyon.setText("POZİSYON");

        lbl_saat.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lbl_saat.setForeground(new java.awt.Color(51, 0, 153));
        lbl_saat.setText("ÇALIŞMA SAATİ");

        cbox_pozisyon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Şef", "Asistan", "Stajyer", " " }));

        btn_personelEkle.setBackground(new java.awt.Color(102, 0, 255));
        btn_personelEkle.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btn_personelEkle.setForeground(new java.awt.Color(255, 255, 102));
        btn_personelEkle.setText("PERSONEL EKLE");
        btn_personelEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_personelEkleActionPerformed(evt);
            }
        });

        lbl_arama.setFont(new java.awt.Font("Helvetica Neue", 3, 16)); // NOI18N
        lbl_arama.setForeground(new java.awt.Color(51, 0, 153));
        lbl_arama.setText("PERSONEL ARAMA");

        btn_ara.setBackground(new java.awt.Color(102, 0, 255));
        btn_ara.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btn_ara.setForeground(new java.awt.Color(255, 255, 102));
        btn_ara.setText("ARA");
        btn_ara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_araActionPerformed(evt);
            }
        });

        btn_izinGunuKontrol.setBackground(new java.awt.Color(102, 0, 255));
        btn_izinGunuKontrol.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btn_izinGunuKontrol.setForeground(new java.awt.Color(255, 255, 102));
        btn_izinGunuKontrol.setText("İZİN GÜNÜ KONTROLÜ");
        btn_izinGunuKontrol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_izinGunuKontrolActionPerformed(evt);
            }
        });

        lbl_id.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lbl_id.setForeground(new java.awt.Color(51, 0, 153));
        lbl_id.setText("ID");

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 153));
        jLabel1.setText("CİNSİYET");

        cbox_fullTime.setText("FULL TIME");

        cbox_cinsiyet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kadın", "Erkek" }));

        btn_maasKontrol.setBackground(new java.awt.Color(102, 0, 255));
        btn_maasKontrol.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btn_maasKontrol.setForeground(new java.awt.Color(255, 255, 102));
        btn_maasKontrol.setText("MAAŞ KONTROLÜ");
        btn_maasKontrol.setMaximumSize(new java.awt.Dimension(178, 23));
        btn_maasKontrol.setMinimumSize(new java.awt.Dimension(178, 23));
        btn_maasKontrol.setPreferredSize(new java.awt.Dimension(178, 23));
        btn_maasKontrol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_maasKontrolActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_yoneticiLayout = new javax.swing.GroupLayout(pnl_yonetici);
        pnl_yonetici.setLayout(pnl_yoneticiLayout);
        pnl_yoneticiLayout.setHorizontalGroup(
            pnl_yoneticiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_yoneticiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_yoneticiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_yoneticiLayout.createSequentialGroup()
                        .addComponent(btn_personelSil, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(btn_personelGuncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_izinGunuKontrol, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_maasKontrol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_yoneticiLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_yoneticiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_yoneticiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(pnl_yoneticiLayout.createSequentialGroup()
                                    .addGroup(pnl_yoneticiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbl_arama)
                                        .addGroup(pnl_yoneticiLayout.createSequentialGroup()
                                            .addGroup(pnl_yoneticiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lbl_adSoyad)
                                                .addComponent(lbl_mail)
                                                .addComponent(lbl_sifre)
                                                .addComponent(lbl_pozisyon)
                                                .addComponent(lbl_id)
                                                .addComponent(jLabel1)
                                                .addComponent(lbl_saat))
                                            .addGap(18, 18, 18)
                                            .addGroup(pnl_yoneticiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(cbox_fullTime)
                                                .addGroup(pnl_yoneticiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(cbox_pozisyon, javax.swing.GroupLayout.Alignment.TRAILING, 0, 242, Short.MAX_VALUE)
                                                    .addComponent(txt_sifre, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(txt_mail, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(txt_adSoyad, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(cbox_cinsiyet, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGap(8, 8, 8))
                                .addComponent(txt_personelArama)
                                .addComponent(btn_ara, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btn_personelEkle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnl_yoneticiLayout.createSequentialGroup()
                        .addComponent(lbl_tablo, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnl_yoneticiLayout.setVerticalGroup(
            pnl_yoneticiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_yoneticiLayout.createSequentialGroup()
                .addGroup(pnl_yoneticiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_yoneticiLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(lbl_tablo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_yoneticiLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnl_yoneticiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_id)
                            .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(pnl_yoneticiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_adSoyad, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_adSoyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnl_yoneticiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_mail))
                        .addGap(18, 18, 18)
                        .addGroup(pnl_yoneticiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_sifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_sifre))
                        .addGap(18, 18, 18)
                        .addGroup(pnl_yoneticiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbox_pozisyon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_pozisyon))
                        .addGap(18, 18, 18)
                        .addGroup(pnl_yoneticiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbox_cinsiyet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(7, 7, 7)
                        .addGroup(pnl_yoneticiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_yoneticiLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(btn_personelEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl_yoneticiLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(pnl_yoneticiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_saat)
                                    .addComponent(cbox_fullTime))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_arama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_personelArama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_ara)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(pnl_yoneticiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_izinGunuKontrol, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_personelGuncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_personelSil, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_maasKontrol, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        getContentPane().add(pnl_yonetici);

        menubar.setBackground(new java.awt.Color(153, 153, 255));

        menu_islemler.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menu_islemler.setText("PERSONEL İŞLEMLERİ");
        menu_islemler.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N

        menui_ekle.setText("Personel Ekle");
        menui_ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menui_ekleActionPerformed(evt);
            }
        });
        menu_islemler.add(menui_ekle);

        menui_güncelle.setText("Personel Güncelle");
        menui_güncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menui_güncelleActionPerformed(evt);
            }
        });
        menu_islemler.add(menui_güncelle);

        menui_sil.setText("Personel Sil");
        menui_sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menui_silActionPerformed(evt);
            }
        });
        menu_islemler.add(menui_sil);

        menubar.add(menu_islemler);

        menu_arama.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menu_arama.setText("PERSONEL ARAMA");
        menu_arama.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        menu_arama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_aramaActionPerformed(evt);
            }
        });
        menubar.add(menu_arama);

        setJMenuBar(menubar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Bu method, kullanicinin gerekli alanlari doldurarak yeni bir personel eklemesini saglar. Mail adresinin dogrulugunu kontrol eder ve veritabanina personeli ekler.  
    private void btn_personelEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_personelEkleActionPerformed

        HacerEbraOzdemir_Personel np1 = new HacerEbraOzdemir_Personel();//Yeni bir "Personel" nesnesi olusturulur ve "np1" degiskenine atanir.
        //Metin kutularındaki ve diğer componentlardaki  biligiler personelin bilgilerine atanir.
        np1.id = Integer.parseInt(txt_id.getText());
        np1.ad_soyad = txt_adSoyad.getText();
        np1.mail = txt_mail.getText();
        np1.sifre = txt_sifre.getText();
        np1.pozisyon = cbox_pozisyon.getSelectedItem().toString();
        np1.calisma_saati = cbox_fullTime.isSelected();
        np1.cinsiyet = cbox_cinsiyet.getSelectedItem().toString();
        try {
            Pattern pattern = Pattern.compile("^([a-z]+\\w*){4,}@{1}((gmail)|(hotmail)){1}(.com){1}$");//Mail icin regex olusturulur ve mail formatının dogrulugunu kontrol etmek icin kullanilir.
            Matcher matcher = pattern.matcher(txt_mail.getText());
            if (matcher.find()) {//Mail gecerliyse;
                HacerEbraOzdemir_DB_PersonelTakip.PersonelEkle(np1);//"np1" nesnesi veritabanina eklenir.
                JOptionPane.showMessageDialog(rootPane, "Personel Eklendi");//Personelin eklendigine dair mesaj gosterilir.
                tbl_model.addRow(new Object[]{np1.id, np1.ad_soyad, np1.pozisyon, np1.mail});//Tablo modeline yeni bir satir eklenir ve personelin bilgileri tabloya eklenir.
                personels.add(np1);//personels arraylistine yeni bir personel eklenir.
            } else {
                JOptionPane.showMessageDialog(rootPane, "Geçersiz mail! Tekrar deneyiniz.");//Gecerli bir mail adresi degilse, hata mesajlari goruntulenir ve personel eklenemez.
                JOptionPane.showMessageDialog(rootPane, "Personel Eklenemedi");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());//Herhangi bir hata durumunda, hata mesaji gonderilir.
        }
    }//GEN-LAST:event_btn_personelEkleActionPerformed

    //Bu method, veritabaninda ilgili personelin bilgilerini guncellemek icin kullanilir. Veritabaninda ilgili personelin bilgileri, yeni girilen bilgilerle degistirilir.
    private void btn_personelGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_personelGuncelleActionPerformed

        //Girilen bilgileri temel alan bir Personel nesnesi olusturulur ve DB_PersonelTakip.PersonelGuncelle() metoduna bu nesne iletilir.
        HacerEbraOzdemir_Personel np1 = new HacerEbraOzdemir_Personel();
        np1.id = Integer.parseInt(txt_id.getText());
        np1.ad_soyad = txt_adSoyad.getText();
        np1.mail = txt_mail.getText();
        np1.sifre = txt_sifre.getText();
        np1.pozisyon = cbox_pozisyon.getSelectedItem().toString();
        np1.calisma_saati = cbox_fullTime.isSelected();
        np1.cinsiyet = cbox_cinsiyet.getSelectedItem().toString();

        HacerEbraOzdemir_DB_PersonelTakip.PersonelGuncelle(np1);
    }//GEN-LAST:event_btn_personelGuncelleActionPerformed

    //Bu method, kullanicinin sectigi bir personeli silmek icin kullanilir. 
    private void btn_personelSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_personelSilActionPerformed

        //Tablodan secilen satirin indeksi ve bu satirdaki personelin ID degeri alinir.
        int rowindex = tbl_personel.getSelectedRow();
        int id = Integer.parseInt(tbl_model.getValueAt(rowindex, 0).toString());

        if (HacerEbraOzdemir_DB_PersonelTakip.IdIlePersonelSil(id)) {//DB_PersonelTakip.IdIlePersonelSil() metoduna bu ID degeri iletilir.
            //Eger personel basariyla silinirse kullaniciya "Personel Silindi" seklinde bir iletisim kutusu gosterilir. Silme islemi basarisiz olursa, kullaniciya "Personel Silinemedi" seklinde bir mesaj gosterilir.
            JOptionPane.showMessageDialog(rootPane, "Personel Silindi");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Personel Sİlinemedi");
        }
    }//GEN-LAST:event_btn_personelSilActionPerformed

    //Bu method, kullanicinin belirli bir metinle personel aramasi yapmasini saglar.
    private void btn_araActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_araActionPerformed

        String arama = txt_personelArama.getText();//txt_personelArama metin alanindan arama icin girilen metin alinir.
        tbl_model.setRowCount(0);//Tablo modelinin satir sayisi sifirlanir (mevcut veriler temizlenir).
        ArrayList<HacerEbraOzdemir_Personel> plist = HacerEbraOzdemir_DB_PersonelTakip.AdVeMailleAra(arama);//DB_PersonelTakip.AdVeMailleAra() metodu kullanilarak, arama metniyle eslesen ad veya e-posta sahibi personellerin bir listesi alinir.

        for (HacerEbraOzdemir_Personel np1 : plist) {//Bu liste uzerinde dongu olusturularak her bir personelin bilgileri tabloya eklenir. 
            tbl_model.addRow(new Object[]{np1.id, np1.ad_soyad, np1.pozisyon, np1.mail});
        }
    }//GEN-LAST:event_btn_araActionPerformed

    private void tbl_personelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_personelMouseClicked

        //Secilen satirin indeksinin kontrolu yapilir. Eger secilen satirin indeksi 0'dan kucukse (yani herhangi bir satir secilmemisse), islem sonlandirilir ve geri dondurur.
        if (tbl_personel.getSelectedRow() < 0) {
            return;
        }
        int id = (int) tbl_model.getValueAt(tbl_personel.getSelectedRow(), 0);//Eger bir satir secilmisse, secilen satirdaki ID degeri alinir. 
        HacerEbraOzdemir_Personel np1 = HacerEbraOzdemir_DB_PersonelTakip.IdIleArama(id);//DB_PersonelTakip.IdIleArama() metodu cagrilir ve ilgili personel bilgileri alinir. 
        //Eger personel bulunmussa, ilgili metin alanlari ve secenekler guncellenir.
        if (np1 != null) {
            txt_id.setText(np1.id + "");
            txt_id.setEnabled(false);
            txt_adSoyad.setText(np1.ad_soyad);
            txt_mail.setText(np1.mail);
            txt_sifre.setText(np1.sifre);
            cbox_fullTime.setSelected(np1.calisma_saati);
            switch (np1.pozisyon) {
                case "Şef":
                    cbox_pozisyon.setSelectedIndex(0);
                    break;
                case "Asistan":
                    cbox_pozisyon.setSelectedIndex(1);
                    break;
                case "Stajyer":
                    cbox_pozisyon.setSelectedIndex(2);
                    break;
            }
            switch (np1.cinsiyet) {
                case "Kadın":
                    cbox_cinsiyet.setSelectedIndex(0);
                    break;
                case "Erkek":
                    cbox_cinsiyet.setSelectedIndex(1);
                    break;
            }
            btn_personelEkle.setEnabled(false);//"Personel Ekle" butonu devre disi birakilir
            //"Personel Guncelle" ve "Personel Sil" butonlari etkinlestirilir.
            btn_personelGuncelle.setEnabled(true);
            btn_personelSil.setEnabled(true);
        }
    }//GEN-LAST:event_tbl_personelMouseClicked

    private void btn_izinGunuKontrolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_izinGunuKontrolActionPerformed

        HacerEbraOzdemir_Personel np1 = new HacerEbraOzdemir_Personel();
        //frm_IzinGunu nesnesi gorunur hale getirilir.
        HacerEbraOzdemir_Frm_IzinGunu frm_IzinGunu = new HacerEbraOzdemir_Frm_IzinGunu(np1);
        frm_IzinGunu.setVisible(true);

    }//GEN-LAST:event_btn_izinGunuKontrolActionPerformed

    private void btn_maasKontrolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_maasKontrolActionPerformed

        //tbl_personel tablosunda secili olan satirdan personelin ID degeri alinir ve id degiskenine atanir.
        int id = (int) tbl_model.getValueAt(tbl_personel.getSelectedRow(), 0);
        HacerEbraOzdemir_Personel np1 = HacerEbraOzdemir_DB_PersonelTakip.IdIleArama(id);//id degeri kullanilarak DB_PersonelTakip.IdIleArama() methodu cagirilir ve ilgili ID'ye sahip personel bilgileri np1 nesnesine atanir.

        if (np1 != null) {
            //np1 nesnesi, Frm_Maas sinifinin bir ornegi olan frm_Maas nesnesine aktarilir ve frm_Maas penceresi gorunur hale getirilir.
            HacerEbraOzdemir_Frm_Maas frm_Maas = new HacerEbraOzdemir_Frm_Maas(np1);
            frm_Maas.setVisible(true);
        }
    }//GEN-LAST:event_btn_maasKontrolActionPerformed

    //Bu method, kullanicinin gerekli alanlari doldurarak yeni bir personel eklemesini saglar. Mail adresinin dogrulugunu kontrol eder ve veritabanina personeli ekler.  
    private void menui_ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menui_ekleActionPerformed

        HacerEbraOzdemir_Personel np1 = new HacerEbraOzdemir_Personel();//Yeni bir "Personel" nesnesi olusturulur ve "np1" degiskenine atanir.
        //Metin kutularındaki ve diğer componentlardaki  biligiler personelin bilgilerine atanir.
        np1.id = Integer.parseInt(txt_id.getText());
        np1.ad_soyad = txt_adSoyad.getText();
        np1.mail = txt_mail.getText();
        np1.sifre = txt_sifre.getText();
        np1.pozisyon = cbox_pozisyon.getSelectedItem().toString();
        np1.calisma_saati = cbox_fullTime.isSelected();
        np1.cinsiyet = cbox_cinsiyet.getSelectedItem().toString();
        try {
            Pattern pattern = Pattern.compile("^([a-z]+\\w*){4,}@{1}((gmail)|(hotmail)){1}(.com){1}$");//Mail icin regex olusturulur ve mail formatının dogrulugunu kontrol etmek icin kullanilir.
            Matcher matcher = pattern.matcher(txt_mail.getText());
            if (matcher.find()) {//Mail gecerliyse;
                HacerEbraOzdemir_DB_PersonelTakip.PersonelEkle(np1);//"np1" nesnesi veritabanina eklenir.
                JOptionPane.showMessageDialog(rootPane, "Personel Eklendi");//Personelin eklendigine dair mesaj gosterilir.
                tbl_model.addRow(new Object[]{np1.id, np1.ad_soyad, np1.pozisyon, np1.mail});//Tablo modeline yeni bir satir eklenir ve personelin bilgileri tabloya eklenir.
                personels.add(np1);//personels arraylistine yeni bir personel eklenir.
            } else {
                JOptionPane.showMessageDialog(rootPane, "Geçersiz mail! Tekrar deneyiniz.");//Gecerli bir mail adresi degilse, hata mesajlari goruntulenir ve personel eklenemez.
                JOptionPane.showMessageDialog(rootPane, "Personel Eklenemedi");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());//Herhangi bir hata durumunda, hata mesaji gonderilir.
        }
    }//GEN-LAST:event_menui_ekleActionPerformed

    //Bu method, veritabaninda ilgili personelin bilgilerini guncellemek icin kullanilir. Veritabaninda ilgili personelin bilgileri, yeni girilen bilgilerle degistirilir.
    private void menui_güncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menui_güncelleActionPerformed

        //Girilen bilgileri temel alan bir Personel nesnesi olusturulur ve DB_PersonelTakip.PersonelGuncelle() metoduna bu nesne iletilir.
        HacerEbraOzdemir_Personel np1 = new HacerEbraOzdemir_Personel();
        np1.id = Integer.parseInt(txt_id.getText());
        np1.ad_soyad = txt_adSoyad.getText();
        np1.mail = txt_mail.getText();
        np1.sifre = txt_sifre.getText();
        np1.pozisyon = cbox_pozisyon.getSelectedItem().toString();
        np1.calisma_saati = cbox_fullTime.isSelected();
        np1.cinsiyet = cbox_cinsiyet.getSelectedItem().toString();

        HacerEbraOzdemir_DB_PersonelTakip.PersonelGuncelle(np1);
    }//GEN-LAST:event_menui_güncelleActionPerformed

    //Bu method, kullanicinin sectigi bir personeli silmek icin kullanilir.
    private void menui_silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menui_silActionPerformed

        //Tablodan secilen satirin indeksi ve bu satirdaki personelin ID degeri alinir.
        int rowindex = tbl_personel.getSelectedRow();
        int id = Integer.parseInt(tbl_model.getValueAt(rowindex, 0).toString());

        if (HacerEbraOzdemir_DB_PersonelTakip.IdIlePersonelSil(id)) {//DB_PersonelTakip.IdIlePersonelSil() metoduna bu ID degeri iletilir.
            //Eger personel basariyla silinirse kullaniciya "Personel Silindi" seklinde bir iletisim kutusu gosterilir. Silme islemi basarisiz olursa, kullaniciya "Personel Silinemedi" seklinde bir mesaj gosterilir.
            JOptionPane.showMessageDialog(rootPane, "Personel Silindi");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Personel Sİlinemedi");
        }
    }//GEN-LAST:event_menui_silActionPerformed

    //Bu method, kullanicinin belirli bir metinle personel aramasi yapmasini saglar.
    private void menu_aramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_aramaActionPerformed

        String arama = txt_personelArama.getText();//txt_personelArama metin alanindan arama icin girilen metin alinir.
        tbl_model.setRowCount(0);//Tablo modelinin satir sayisi sifirlanir (mevcut veriler temizlenir).
        ArrayList<HacerEbraOzdemir_Personel> plist = HacerEbraOzdemir_DB_PersonelTakip.AdVeMailleAra(arama);//DB_PersonelTakip.AdVeMailleAra() metodu kullanilarak, arama metniyle eslesen ad veya e-posta sahibi personellerin bir listesi alinir.

        for (HacerEbraOzdemir_Personel np1 : plist) {//Bu liste uzerinde dongu olusturularak her bir personelin bilgileri tabloya eklenir. 
            tbl_model.addRow(new Object[]{np1.id, np1.ad_soyad, np1.pozisyon, np1.mail});
        }
    }//GEN-LAST:event_menu_aramaActionPerformed
    /**/
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ara;
    private javax.swing.JButton btn_izinGunuKontrol;
    private javax.swing.JButton btn_maasKontrol;
    private javax.swing.JButton btn_personelEkle;
    private javax.swing.JButton btn_personelGuncelle;
    private javax.swing.JButton btn_personelSil;
    private javax.swing.ButtonGroup btngroup_cinsiyet;
    private javax.swing.ButtonGroup btngroup_saat;
    private javax.swing.JComboBox<String> cbox_cinsiyet;
    private javax.swing.JCheckBox cbox_fullTime;
    private javax.swing.JComboBox<String> cbox_pozisyon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_adSoyad;
    private javax.swing.JLabel lbl_arama;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_mail;
    private javax.swing.JLabel lbl_pozisyon;
    private javax.swing.JLabel lbl_saat;
    private javax.swing.JLabel lbl_sifre;
    private javax.swing.JLabel lbl_tablo;
    private javax.swing.JMenu menu_arama;
    private javax.swing.JMenu menu_islemler;
    private javax.swing.JMenuBar menubar;
    private javax.swing.JMenuItem menui_ekle;
    private javax.swing.JMenuItem menui_güncelle;
    private javax.swing.JMenuItem menui_sil;
    private javax.swing.JPanel pnl_yonetici;
    private javax.swing.JTable tbl_personel;
    private javax.swing.JTextField txt_adSoyad;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_mail;
    private javax.swing.JTextField txt_personelArama;
    private javax.swing.JPasswordField txt_sifre;
    // End of variables declaration//GEN-END:variables
}
